"""Corrige relación entre OrdenTrabajo y Aplicacion

Revision ID: 8d8fae0c2bbe
Revises: a33ce9bd2cf0
Create Date: 2025-11-09 21:29:37.582645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8fae0c2bbe'
down_revision = 'a33ce9bd2cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=100), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('cantidad_por_hectarea', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('aplicaciones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplicaciones',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('orden_id', sa.INTEGER(), nullable=False),
    sa.Column('producto', sa.VARCHAR(length=100), nullable=False),
    sa.Column('unidad', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cantidad_por_hectarea', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('aplicacion')
    # ### end Alembic commands ###
