"""Agrega relación aplicaciones a OrdenTrabajo

Revision ID: a33ce9bd2cf0
Revises: 
Create Date: 2025-11-09 21:23:08.623203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33ce9bd2cf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=100), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('cantidad_por_hectarea', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.drop_column('producto_aplicado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_aplicado', sa.VARCHAR(length=100), nullable=False))

    op.drop_table('aplicaciones')
    # ### end Alembic commands ###
