"""Agrega ForeignKey orden_id en Aplicacion

Revision ID: b88f65804ed5
Revises: 8d8fae0c2bbe
Create Date: 2025-11-09 21:32:21.667980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88f65804ed5'
down_revision = '8d8fae0c2bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_aplicacion_orden_id', 'orden_trabajo', ['orden_id'], ['id'])
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('orden_id')

    # ### end Alembic commands ###
