"""Migración completa desde cero

Revision ID: d689d1c93c65
Revises: 
Create Date: 2025-11-14 01:18:37.080389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd689d1c93c65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productor_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('hectareas', sa.Float(), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['productor_id'], ['productor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aplicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('producto', sa.String(length=100), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('cantidad_por_hectarea', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aplicacion')
    op.drop_table('orden_trabajo')
    op.drop_table('productor')
    # ### end Alembic commands ###
